### PR TITLE
fix: silkscreen component to follow parent layer

### LINKED ISSUE #688: Silkscreen lines don't move to bottom silkscreen layer when you do `layer="bottom"` on a component
Image

### PR DESCRIPTION
**Pull request by Ayushjhawar8**
/claim #688
close #688 

image

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
is there a bug in circuit-to-svg that doesn't draw silkscreen on the bottom layer properly? Can you file an issue for that , the snapshot isn't right which is a bit confusing.

**Comment by seveibar** [comment]
make sure to rerun/get tests passing on ci

File: lib/utils/get-bounds-of-pcb-components.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ export function getBoundsOfPcbComponents(components: PrimitiveComponent[]) {
   let maxY = -Infinity
 
   for (const child of components) {
-    if (child.isPcbPrimitive && child.componentName !== "SilkscreenText") {
+    if (child.isPcbPrimitive && !child.componentName.startsWith("Silkscreen")) {
```
Comment (Ayushjhawar8) [inline lib/utils/get-bounds-of-pcb-components.ts:10]: @seveibar i made thing change as Adding `isPcbPrimitive = true` to silkscreen components unintentionally included them in the PCB component size calculation. So i modified getBoundsOfPcbComponents() to exclude all components whose names start with "Silkscreen," not just SilkscreenText.

This ensures that silkscreen elements respect their parent component's layer without impacting the component's dimensions in the PCB layout. 

Now all test are passing. Please check

**Comment by Ayushjhawar8** [comment]
> is there a bug in circuit-to-svg that doesn't draw silkscreen on the bottom layer properly? Can you file an issue for that , the snapshot isn't right which is a bit confusing.

i think there is the issue with the circuit-to-svg as the test is accurate i believe

**Comment by seveibar** [comment]
@Ayushjhawar8 can you make sure you merge with latest main, i think one of your snapshots is a bit old. We should fix the issue in circuit-to-svg before merging this imo, but the PR looks good

**Comment by seveibar** [comment]
it's hard to tell if this is working properly without the bottom silkscreen implemented on circuit-to-svg. Keep in mind, bottom silkscreen text is reflected (imagine: it's on the bottom of the board so you would have to "flip the board to the back" for it to display properly)

image

**Comment by Ayushjhawar8** [comment]
unstaling

**Comment by Ayushjhawar8** [comment]
unstale

**Review by seveibar — APPROVED** [review]
Do you have a snapshot test for this somewhere?

**Comment by Ayushjhawar8** [comment]
image

File: tests/components/primitive-components/silkscreen-component-layer.test.tsx
Comment (Ayushjhawar8) [inline tests/components/primitive-components/silkscreen-component-layer.test.tsx:1]: this is the test

Comment (Ayushjhawar8) [reply tests/components/primitive-components/silkscreen-component-layer.test.tsx:1]: its snapshot:
image

Comment (Ayushjhawar8) [reply tests/components/primitive-components/silkscreen-component-layer.test.tsx:1]:
```
import { expect, test } from "bun:test"
import { getTestFixture } from "tests/fixtures/get-test-fixture"

test("silkscreen components should respect parent component layer", () => {
  const { project } = getTestFixture()
  project.add(
    <board width="10mm" height="10mm">
      <group layer="bottom">
        {/* Test all silkscreen primitives respect parent layer */}
        <silkscreenline x1={0} y1={0} x2={5} y2={5} strokeWidth={0.2} />
        <silkscreentext text="Test" pcbX={2} pcbY={2} />
        <silkscreenrect width={2} height={2} pcbX={4} pcbY={4} />
        <silkscreenpath
          route={[
            { x: 0, y: 0 },
            { x: 2, y: 2 },
            { x: 4, y: 0 },
          ]}
          strokeWidth={0.2}
        />
      </group>
    </board>,
  )
  project.render()

  // Check silkscreen line
  const lines = project.db.pcb_silkscreen_line.list()
  expect(lines.length).toBe(1)
  expect(lines[0].layer).toBe("bottom")

  // Check silkscreen text
  const texts = project.db.pcb_silkscreen_text.list()
  expect(texts.length).toBe(1)
  expect(texts[0].layer).toBe("bottom")

  // Check silkscreen rect
  const rects = project.db.pcb_silkscreen_rect.list()
  expect(rects.length).toBe(1)
  expect(rects[0].layer).toBe("bottom")

  // Check silkscreen path
  const paths = project.db.pcb_silkscreen_path.list()
  expect(paths.length).toBe(1)
  expect(paths[0].layer).toBe("bottom")

  expect(project).toMatchPcbSnapshot(import.meta.path)
})
```

Comment (Ayushjhawar8) [reply tests/components/primitive-components/silkscreen-component-layer.test.tsx:1]: its snapshot:
image

Comment (Ayushjhawar8) [reply tests/components/primitive-components/silkscreen-component-layer.test.tsx:1]: also these one have changed see 
image
