### PR TITLE
fix: Capacitors don't render with schRotation of negative angles

### LINKED ISSUE #482: Capacitors don't render with schRotation="-90deg"
/bounty $3

Currently, the schRotation supports multiples of 90, like 180, 270, 360. We need to support the -ve case as well instead of 270 user can use -90 as well

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #482 
Fixes #482 

image

### CODE REVIEW

**Comment by Anshgrover23** [comment]
@Abse2001 done.

**Review by Abse2001 — APPROVED** [review]
nice work

File: lib/components/base-components/PrimitiveComponent.ts [hunk 1]
```diff
@@ -302,6 +302,24 @@ export abstract class PrimitiveComponent<
     const base_symbol_name = this.config
       .schematicSymbolName as keyof typeof symbols
 
+    // normalize the rotation
+    let rawRotation = props.schRotation
```
Comment (seveibar) [inline lib/components/base-components/PrimitiveComponent.ts:306]:
```suggestion
    let normalizedRotation = props.schRotation
```

File: tests/components/primitive-components/schematic-neg-schRotation.test.tsx [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+        name="C1"
+        capacitance="100nF"
+        footprint="0402"
+        schRotation={-360}
+      />
+    </board>,
+  )
+  circuit.render()
+  expect(circuit).toMatchSchematicSnapshot("neg-360-" + import.meta.path)
+})
```
Comment (seveibar) [inline tests/components/primitive-components/schematic-neg-schRotation.test.tsx:70]: can you put these on the same snapshot svg

File: tests/components/primitive-components/schematic-neg-schRotation.test.tsx [hunk 3]
```diff
@@ -0,0 +1,47 @@
+import { it, expect } from "bun:test"
+import { getTestFixture } from "tests/fixtures/get-test-fixture"
+
+it("should render rotated versions of capacitors", async () => {
+  const { circuit } = getTestFixture()
+
+  circuit.add(
+    <board width="20mm" height="20mm">
+      <capacitor
+        name="C1"
```
Comment (seveibar) [inline tests/components/primitive-components/schematic-neg-schRotation.test.tsx:10]:
```suggestion
        name="C1_n90"
```

File: tests/components/primitive-components/schematic-neg-schRotation.test.tsx [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+        schY={0}
+        schX={3}
+        capacitance="10k"
+        schRotation={-90}
+      />
+
+      <capacitor
+        name="C2"
```
Comment (seveibar) [inline tests/components/primitive-components/schematic-neg-schRotation.test.tsx:18]:
```suggestion
        name="C2_n180"
```

File: tests/components/primitive-components/schematic-neg-schRotation.test.tsx [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+it("should render rotated versions of capacitors", async () => {
+  const { circuit } = getTestFixture()
+
+  circuit.add(
+    <board width="20mm" height="20mm">
+      <capacitor
+        name="C1"
+        schY={0}
+        schX={3}
+        capacitance="10k"
```
Comment (seveibar) [inline tests/components/primitive-components/schematic-neg-schRotation.test.tsx:13]:
```suggestion
        capacitance="10uF"
```

**Review by seveibar — COMMENTED** [review]
minor changes, rename capacitors, make sure capacitors have realistic values (10uF, 1uF)

File: tests/components/primitive-components/schematic-neg-schRotation.test.tsx [hunk 6]
```diff
@@ -0,0 +1,47 @@
+import { it, expect } from "bun:test"
+import { getTestFixture } from "tests/fixtures/get-test-fixture"
+
+it("should render rotated versions of capacitors", async () => {
+  const { circuit } = getTestFixture()
+
+  circuit.add(
+    <board width="20mm" height="20mm">
+      <capacitor
+        name="C1_90"
```
Comment (seveibar) [inline tests/components/primitive-components/schematic-neg-schRotation.test.tsx:10]:
```suggestion
        name="C1_n90"
```

File: tests/components/primitive-components/schematic-neg-schRotation.test.tsx [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+
+      <capacitor
+        name="C4_360"
+        schY={3}
+        schX={3}
+        capacitance="10µF"
+        schRotation={-360}
+      />
+
+      <capacitor name="C5" schY={3} schX={6} capacitance="10µF" />
```
Comment (seveibar) [inline tests/components/primitive-components/schematic-neg-schRotation.test.tsx:41]:
```suggestion
      <capacitor name="C5_none" schY={3} schX={6} capacitance="10µF" />
```

**Review by seveibar — APPROVED** [review]
