### PR TITLE
fix: Handle parts engine errors gracefully and expose them in Circuit JSON

### LINKED ISSUE #1400: Handle errors inside the parts engine gracefully
Image

### PR DESCRIPTION
**Pull request by Ayushjhawar8**
fix #1400 
/claim #1400

### CODE REVIEW

File: lib/components/base-components/NormalComponent/NormalComponent.ts [hunk 1]
```diff
@@ -1423,35 +1423,79 @@ export class NormalComponent<
...
+      const errorMessage =
+        error instanceof Error ? error.message : String(error)
+      debug(
+        `Error fetching supplier part numbers for ${source_component.name}: ${errorMessage}`,
+      )
+
+      // Insert error into Circuit JSON for user visibility
+      if (this.root?.db) {
+        this.root.db.pcb_placement_error.insert({
+          error_type: "pcb_placement_error",
```
Comment (seveibar) [inline lib/components/base-components/NormalComponent/NormalComponent.ts]: not a placement error

**Review by seveibar — CHANGES_REQUESTED** [review]
avoid large try catch blocks, instead, do `.catch(` on the relevant promise to the parts engine

File: lib/components/base-components/NormalComponent/NormalComponent.ts [hunk 2]
```diff
@@ -1443,8 +1444,37 @@ export class NormalComponent<
...
     )
 
-    // Convert "Not found" to empty object before caching or returning
-    const supplierPartNumbers = result === "Not found" ? {} : result
+    // Validate the result format
+    if (typeof result === "string") {
+      // Check if it's an HTML error page or "Not found"
+      if (result.includes("<!DOCTYPE") || result.includes("<html")) {
+        throw new Error(
+          `Failed to fetch supplier part numbers: Received HTML response instead of JSON. Response starts with: ${result.substring(0, 100)}`,
```
Comment (seveibar) [inline lib/components/base-components/NormalComponent/NormalComponent.ts]: VERY NICE HANDLING!!!!!!!!!

**Review by seveibar — APPROVED** [review]
NICELY DONE!!!!!
