### PR TITLE
fixed double schematic traces

### LINKED ISSUE #740: Schematic Trace crossing "hop" generated incorrectly in some cases
You MUST reproduce prior to fixing in a snapshot test to claim bounty

Image

/bounty $20

### LINKED ISSUE #754: Fix repro13 test: Schematic Trace crossing "hop" generated incorrectly in some cases
The repro13 test already demonstrates the issue

CC @Abse2001 

/bounty $20

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**
two bounties were made for the same issue

/claim #754
/closes #754
/closes #740
/claim #740

### CODE REVIEW

File: lib/components/normal-components/Board.ts [hunk 1]
```diff
@@ -31,6 +32,10 @@ export class Board extends Group<typeof boardProps> {
     return ["top", "bottom", "inner1", "inner2"]
   }
 
+  getConnectedSchematicPortPairs(): Set<string> {
+    return this._connectedSchematicPortPairs
```
Comment (seveibar) [inline lib/components/normal-components/Board.ts:36]: No need for this fn

File: lib/components/primitive-components/Trace/Trace.ts [hunk 2]
```diff
@@ -238,6 +241,32 @@ export class Trace
...
+    } else if ("path" in props) {
+      direction = props.path.join("->")
+    } else {
+      const portNames = sortedPorts.map((p) => p.pcb_port_id).join("->")
+      direction = portNames
+    }
+
+    if (!direction) return null
+
+    return `${allIds.join(",")}:${direction}`
```
Comment (seveibar) [inline lib/components/primitive-components/Trace/Trace.ts:267]: Why do we need direction? I dont think it matters

**Review by seveibar — COMMENTED** [review]
AMAZING minor requests

File: lib/components/normal-components/Board.ts (hunk 1 above)
Comment (ShiboSoftwareDev) [reply lib/components/normal-components/Board.ts:36]: Ghost code

File: lib/components/primitive-components/Trace/Trace.ts (hunk 2 above)
Comment (ShiboSoftwareDev) [reply lib/components/primitive-components/Trace/Trace.ts:267]: Again ghost code, I need to review myself before asking for review. Just some basic skills I lost

**Review by seveibar — APPROVED** [review]
awesome!
